import os
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from datetime import datetime

class STRGenerator:
    def __init__(self):
        self.reports_dir = os.path.join(os.path.dirname(__file__), 'reports')
        os.makedirs(self.reports_dir, exist_ok=True)

    def generate(self, alert):
        alert_id = alert['alert_id']
        file_path = os.path.join(self.reports_dir, f"STR_{alert_id}.pdf")
        
        doc = SimpleDocTemplate(file_path, pagesize=letter)
        styles = getSampleStyleSheet()
        
        # Custom styles
        title_style = ParagraphStyle('TitleStyle', parent=styles['Heading1'], alignment=1, textColor=colors.darkblue)
        heading_style = ParagraphStyle('HeadingStyle', parent=styles['Heading2'], textColor=colors.maroon)
        normal_style = styles['Normal']
        
        elements = []
        
        # Header
        elements.append(Paragraph("SUSPICIOUS TRANSACTION REPORT — FIU-IND FORMAT", title_style))
        elements.append(Spacer(1, 12))
        
        # Metadata
        elements.append(Paragraph(f"<b>Report ID:</b> STR-{alert_id}", normal_style))
        elements.append(Paragraph(f"<b>Date Generated:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S IST')}", normal_style))
        elements.append(Paragraph("<b>Reporting Bank:</b> Union Bank of India (GraphSent Demo)", normal_style))
        elements.append(Paragraph("<b>System:</b> Auto-generated by GraphSent AI", normal_style))
        elements.append(Spacer(1, 20))
        
        # Section 1
        elements.append(Paragraph("Section 1: Subject Account Details", heading_style))
        elements.append(Paragraph(f"<b>Account ID:</b> {alert['account_id']}", normal_style))
        elements.append(Paragraph(f"<b>Customer ID:</b> {alert['customer_id']}", normal_style))
        elements.append(Spacer(1, 12))
        
        # Section 3
        elements.append(Paragraph("Section 2: Risk Analysis", heading_style))
        elements.append(Paragraph(f"<b>Composite Risk Score:</b> {alert['composite_risk_score']} out of 1.0", normal_style))
        elements.append(Paragraph(f"<b>Risk Tier:</b> {alert['risk_tier']}", normal_style))
        
        data = [["Detector Model", "Score (0-1)"]]
        for k, v in alert.get('individual_scores', {}).items():
            data.append([k, f"{v:.2f}"])
            
        t = Table(data, colWidths=[200, 100])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1a2744')),
            ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0,0), (-1,0), 12),
            ('BACKGROUND', (0,1), (-1,-1), colors.beige),
            ('GRID', (0,0), (-1,-1), 1, colors.black)
        ]))
        elements.append(t)
        elements.append(Spacer(1, 20))
        
        # Section 4
        elements.append(Paragraph("Section 3: Triggered Reasons", heading_style))
        for r in alert.get('reasons', []):
            elements.append(Paragraph(f"• {r}", normal_style))
        elements.append(Spacer(1, 20))
        
        # Section 5
        elements.append(Paragraph("Section 4: Recommended Action", heading_style))
        elements.append(Paragraph(f"<b>ACTION REQUIRED:</b> {alert['recommended_action']}", normal_style))
        elements.append(Spacer(1, 40))
        
        # Footer
        elements.append(Paragraph("<i>Auto-generated by GraphSent AI — For investigator review only</i>", ParagraphStyle('Footer', parent=styles['Normal'], alignment=1)))
        
        doc.build(elements)
        return file_path
